--- #YAML:1.0
name:                CIAO-Lib-Param
version:             0.08
abstract:            an interface to the CIAO parameter library.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Diab Jerius <dj@cfa.harvard.edu>
